# Generated by Django 5.0.7 on 2024-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='OS',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Linux', 'Linux'), ('Windows', 'Windows')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.CharField(choices=[('Enumeration', 'Enumeration'), ('Foothold', 'Foothold'), ('Privilege escalation', 'Privesc'), ('Rooted', 'Rooted')], default='Enumeration', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
