# Generated by Django 5.0.7 on 2024-07-23 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_methodology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='methodology',
            old_name='service',
            new_name='related_service',
        ),
        migrations.AddField(
            model_name='service',
            name='methodology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.methodology'),
        ),
    ]
