# Generated by Django 3.0 on 2024-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_rename_service_methodology_related_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('Capture the flag', 'Ctf'), ('Bug bounty', 'Bugbounty'), ('In the wild', 'Wild')], default='In the wild', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
