# Generated by Django 3.0 on 2024-07-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20240725_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='type',
            new_name='typeTarget',
        ),
    ]
