# Generated by Django 3.0 on 2024-07-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20240725_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='typeTarget',
        ),
    ]
