# Generated by Django 4.2.14 on 2024-07-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_case_id_alter_methodology_id_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='type_target',
            field=models.CharField(choices=[('CTF', 'Ctf'), ('Bug bounty', 'Bug Bounty'), ('In the wild', 'In The Wild')], default='In the wild', max_length=20),
        ),
    ]
