# Generated by Django 4.2.14 on 2024-07-27 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_case_type_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='type_target',
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_target',
            field=models.CharField(choices=[('CTF', 'Ctf'), ('Bug bounty', 'Bug Bounty'), ('In the wild', 'In The Wild'), ('Not defined', 'Undefined')], default='Not defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 7, 27), null=True),
        ),
    ]
