# Generated by Django 4.2.14 on 2024-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_case_type_target_case_type_of_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type_of_target',
            field=models.CharField(choices=[('Capture the flag', 'Ctf'), ('Bug bounty', 'Bug Bounty'), ('In the wild', 'In The Wild'), ('Not defined', 'Undefined')], default='Not defined', max_length=20),
        ),
    ]
