# Generated by Django 4.2.14 on 2024-07-29 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_case_type_of_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 7, 29), null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_of_target',
            field=models.CharField(choices=[('Capture the flag', 'Capture The Flag'), ('Bug bounty', 'Bug Bounty'), ('In the wild', 'In The Wild'), ('Not defined', 'Not Defined')], default='Not defined', max_length=20),
        ),
    ]
