# Generated by Django 4.2.14 on 2024-07-31 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_service_case_alter_case_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 7, 31), null=True),
        ),
    ]
