# Generated by Django 4.2.14 on 2024-08-01 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_case_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='case',
            new_name='linked_case',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='methodology',
            new_name='linked_methodology',
        ),
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 1), null=True),
        ),
    ]
