# Generated by Django 4.2.14 on 2024-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_remove_service_address_alter_case_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
