# Generated by Django 4.2.14 on 2024-08-02 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_service_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
