# Generated by Django 4.2.14 on 2024-08-02 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_alter_service_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
