# Generated by Django 5.0.7 on 2024-08-11 17:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_service_name_alter_service_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodology',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='related_service',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='version',
        ),
        migrations.AddField(
            model_name='methodology',
            name='related_port',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 11), null=True),
        ),
    ]
