# Generated by Django 5.0.7 on 2024-08-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_remove_methodology_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodology',
            name='cve',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='urls',
        ),
    ]
