# Generated by Django 5.0.7 on 2024-08-14 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_remove_methodology_cve_remove_methodology_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 14), null=True),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
