# Generated by Django 5.0.7 on 2024-08-15 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_case_last_update_alter_methodology_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 15), null=True),
        ),
    ]
