# Generated by Django 5.0.7 on 2024-08-17 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_alter_case_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 17), null=True),
        ),
    ]
