# Generated by Django 5.0.7 on 2024-08-17 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_alter_case_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
