# Generated by Django 5.0.7 on 2024-08-18 16:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_alter_service_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 18), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
