# Generated by Django 5.0.7 on 2024-08-19 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_alter_case_last_update_alter_service_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 19), null=True),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
