# Generated by Django 5.0.7 on 2024-08-22 14:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_alter_case_last_update_alter_methodology_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 8, 22), null=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=280, null=True)),
                ('date', models.DateField(default=datetime.date(2024, 8, 22))),
                ('linked_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.case')),
            ],
        ),
    ]
