# Generated by Django 5.0.7 on 2024-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_alter_case_last_update_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
