# Generated by Django 5.0.7 on 2024-09-07 18:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 9, 7), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 7)),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(null=True)),
                ('linked_methodology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.methodology')),
            ],
        ),
    ]
