# Generated by Django 5.0.7 on 2024-09-13 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_alter_case_last_update_alter_note_date_ressource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=7, null=True)),
                ('text', models.CharField(max_length=20000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 9, 13), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 13)),
        ),
    ]
