# Generated by Django 5.0.7 on 2024-09-15 10:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_privesc_alter_case_last_update_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 9, 15), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 15)),
        ),
        migrations.CreateModel(
            name='SpecialPrivesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('url', models.URLField(null=True)),
                ('linked_os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.privesc')),
            ],
        ),
    ]
